"""Auto-tuned block sizes for the MLA v2 Pallas kernel.

The MLA v2 kernel (`mla_ragged_paged_attention`) accepts three block-size slots
indexed `(decode, prefill, mixed)`, but the entry function dispatches the three
pallas_calls as `(BATCHED_DECODE, DECODE-tail, MIXED)`:

  - BATCHED_DECODE and DECODE-tail share slot[0]
  - slot[1] (PREFILL) is currently dead code (kernel.py TODO)
  - MIXED uses slot[2]

So the table only carries two `case_label` buckets:

  - "decode": one entry covers slot[0] AND `decode_batch_size`
  - "mixed":  one entry covers slot[2]

Schema:
    TUNED_BLOCK_SIZES_MLA[device_name][key] = config_tuple
    key = (case_label, q_dtype, kv_dtype, num_q_heads, kv_lora_rank,
           qk_rope_head_dim, page_size, max_num_tokens)
    case_label in {"decode", "mixed"}
    config_tuple ("decode") = (num_kv_pages_per_block, num_queries_per_block,
                               decode_batch_size)
    config_tuple ("mixed")  = (num_kv_pages_per_block, num_queries_per_block)

`num_q_heads`, `page_size`, `max_num_tokens` are normalized via `next_power_of_2`
to bucket nearby shapes. `kv_lora_rank` / `qk_rope_head_dim` are passed through
unchanged (they are model constants, not runtime-variable).

Generated by `benchmark/kernels/mla/get_block_spec_config_mla.py`.
"""

from __future__ import annotations

import logging

import jax.numpy as jnp

from sgl_jax.srt.kernels.ragged_paged_attention.util import (
    align_to,
    get_dtype_packing,
    get_tpu_version,
    next_power_of_2,
)
from sgl_jax.srt.utils.jax_utils import get_device_name

logger = logging.getLogger(__name__)

# Track which (case, key) combos we've already warned about, so each unique
# lookup miss prints at most once per process. Helps diagnose "tuned table
# was added but server still falls back to default" bugs (usually a shape
# mismatch — wrong q_heads_per_shard, wrong page_size, or wrong mnt bucket).
_WARNED_MISSES: set[tuple] = set()

# Schema: see module docstring.
TUNED_BLOCK_SIZES_MLA: dict[str, dict[tuple, tuple]] = {
    "TPU v5": {},
    "TPU v6e": {
        # ===== DeepSeek-V3 (kv_lora_rank=512, qk_rope_head_dim=64) =====
        # Deploy: --tp-size 64 --dp-size 8 --page-size 128
        # → attention_tp = 8 → per-shard num_q_heads = 128/8 = 16.
        # Tuned 2026-06-05 on chavoshi-us-east5-b-2 v6e-64 via
        # benchmark/kernels/mla/get_block_spec_config_mla.py (kv_len=4096).
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 1): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 8): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 16): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 32): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 64): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 128): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 256): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 512): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 1024): (32, 1, 2),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 1): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 8): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 16): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 32): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 64): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 128): (16, 128),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 256): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 512): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 1024): (8, 256),
        # ===== GLM-5.2 (kv_lora_rank=512, qk_rope_head_dim=64) =====
        # Deploy: --tp-size 64 --dp-size 8 --page-size 128
        # → attention_tp = 8 → per-shard num_q_heads = 64/8 = 8.
        # Transitional values (#1546): borrowed row-for-row from the DSv3
        # 16-head family above; validated on a v6e-64 slice with a paired
        # eval + throughput sweep up to concurrency 460 (zero Mosaic
        # errors). A tuner sweep should replace these.
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 1): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 8): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 16): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 32): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 64): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 128): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 256): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 512): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 128, 1024): (32, 1, 2),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 1): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 8): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 16): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 32): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 64): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 128): (16, 128),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 256): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 512): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 1024): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 2048): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 4096): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 128, 8192): (8, 256),
    },
    "TPU v7": {
        # ===== Ling-2.6-1T (kv_lora_rank=512, qk_rope_head_dim=64) =====
        # Production deploy: --tp-size 32 --dp-size 4 --page-size 256
        # → attention_tp = tp/dp = 8 → per-shard num_q_heads = 64/8 = 8.
        # Server-jit per-shard mnt buckets (= global / dp_size=4):
        #   decode bs_buckets = [64,128,256,512] → per-shard mnt {16,32,64,128}
        #   mixed token_buckets = [512,1024,2048,4096,8192]
        #     → per-shard mnt {128,256,512,1024,2048}
        # Steady-state hot for 16k input + chunked-prefill=2048:
        #   prefill chunk per-shard mnt = 2048/4 = 512 (mixed case)
        #   decode per-shard mnt depends on running req count (∈ above)
        #
        # Tuned 2026-05-29 on falcon exp-vj0fm1psbw (single v7x host, 8 cores)
        # against hardcoded heuristic decode=(3,1,4) / mixed=(1,16).
        # Tuner uses scope-name-matched extraction of pallas_call
        # device_duration_ps (matches the kernel's `MLA-bd-...` /
        # `MLA-m-...` named_scope) → pure kernel device time.
        # Cross-validated: production profiling shows decode dp=4 tp=8 with
        # 128-concurrency (per-DP 32) ≈ 350us; tuner heur (3,1,4) at
        # mnt=32 measured 347us — match.
        #
        # Wins (pure kernel device time):
        #   decode mnt=16:  +16.2%  (0.147ms vs 0.176ms)
        #   decode mnt=32:  +18.1%  (0.284ms vs 0.347ms)
        #   decode mnt=64:  +19.4%  (0.557ms vs 0.691ms)
        #   decode mnt=128: +20.0%  (1.104ms vs 1.380ms)
        #   mixed mnt=512:  +85.6%  (0.266ms vs 1.841ms)
        #   mixed mnt=1024: +86.2%  (0.546ms vs 3.966ms)
        #   mixed mnt=2048: +87.2%  (1.162ms vs 9.065ms)  ← user prefill chunk
        #   mixed mnt=4096: +88.4%  (2.616ms vs 22.638ms)
        #
        # See benchmark/kernels/mla/get_block_spec_config_mla.py.
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 256, 16): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 256, 32): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 256, 64): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 256, 128): (32, 1, 2),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 256, 512): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 256, 1024): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 256, 2048): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 256, 4096): (8, 256),
        # ===== Ling-3.0-Tiny (16 q-heads, TP8/DP8 → attention TP=1, page=256) =====
        # The table key does not include actual KV length, so these are minimax
        # choices that beat the fallback at both KV=2048 and KV=8192. Kernel
        # latency reductions versus mixed=(1,16):
        #   mnt=64:  (16,32), 13.5% / 25.3%
        #   mnt=128: (8,16),  31.5% / 33.3%
        #   mnt=256: (4,64),  35.3% / 35.4%
        # Decode winners changed with KV length (or stayed below 10%), so no
        # Ling-3 decode entries are installed from this sweep.
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 256, 64): (16, 32),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 256, 128): (8, 16),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 256, 256): (4, 64),
        # ===== GLM-5.3-Flash DP1 / DP2 / 200K =====
        # 同一批调优（2026-09-10，.127 / .117 单机 8 device，kv_len=204800）。
        # attention_tp = tp/dp 决定每 rank 的 Q head 数：dp1 -> 4，dp2 -> 8。
        # per-shard mnt 与 dp 无关（= chunked-prefill-size 及其下层桶）。
        # 热点 mnt=16384 的纯 kernel 时间随 head 数近似线性：
        #   4 head 66.5ms / 8 head 120.4ms / 16 head 229.9ms
        # 相对启发式的提升：mixed +73~97%，decode +32~68%。
        # 注意 4/8 head 的最优 bkv_p 是 32，和 16 head 的 8 不同，不能互相套用。
        #
        # 2026-09-12 复扫：上一批的 bq 上限 256 是 get_block_spec_config_mla.py 里
        # `_BQ_MIXED_CANDIDATES` 的网格天花板，不是最优点。bq 决定整条 KV 被重复
        # 读几遍（num_bq = mnt/bq），200K 下这笔 HBM 流量很可观。放开网格后
        # 4 head / mnt=16384 的最优点移到 (8, 1024) = 57.5ms，比 (32, 256) 的
        # 66.5ms 快 13.6%。bq=2048 起全部 SKIP_VMEM（acc/l/m/q 四个 ref 就吃掉
        # ~44MB，超过 57.6MiB 上限）。三个热点桶都是 (8, 1024) 最优：
        #   mnt=4096  14.81 -> 13.90ms (+6.1%)
        #   mnt=8192  30.74 -> 28.08ms (+8.7%)
        #   mnt=16384 66.55 -> 57.52ms (+13.6%)
        # 复现：get_block_spec_config_mla.py --cases mixed --num-q-heads 4
        #       --page-sizes 64 --mixed-mnt 16384 --mixed-kv-len 204800
        #       --mixed-bq 128,256,512,1024,2048 --mixed-bkv-p 1,2,4,8,16,32
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 1): (32, 1),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 2): (32, 1),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 4): (32, 4),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 8): (32, 8),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 16): (32, 16),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 32): (32, 32),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 64): (32, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 4096): (8, 1024),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 8192): (8, 1024),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 64, 16384): (8, 1024),
        ("decode", "bfloat16", "bfloat16", 4, 512, 64, 64, 1): (32, 1, 1),
        ("decode", "bfloat16", "bfloat16", 4, 512, 64, 64, 2): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 4, 512, 64, 64, 4): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 4, 512, 64, 64, 8): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 4, 512, 64, 64, 16): (32, 1, 8),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 1): (32, 1),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 2): (32, 1),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 4): (32, 4),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 8): (32, 8),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 16): (32, 16),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 32): (32, 32),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 64): (32, 64),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 4096): (32, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 8192): (32, 256),
        ("mixed", "bfloat16", "bfloat16", 8, 512, 64, 64, 16384): (32, 256),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 64, 1): (32, 1, 1),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 64, 2): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 64, 4): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 64, 8): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 8, 512, 64, 64, 16): (32, 1, 4),
        # MIXED-only 的 prefill 调用里，wrapper 会连带发出零工作量的 decode 槽。
        # 照抄硬编码 fallback，只为让 lookup 审计干净（HLO 不变，不触发重编译）。
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 64, 4096): (3, 1, 4),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 64, 8192): (3, 1, 4),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 64, 16384): (3, 1, 4),
        # ===== GLM-5.3-Flash DP4 / 200K (dense MLA layers; DSA 未实现，11 层
        # 走 fa 回退到 MLA v2) =====
        # 部署：--tp-size 16 --dp-size 4 --page-size 64 => attention_tp=4，
        # 每 rank 64/4 = 16 个 Q head。per-shard mnt = 全局桶 / dp_size：
        #   prefill  chunked-prefill=16384，全局桶 [16384,32768,65536]
        #            -> mixed mnt {4096, 8192, 16384}
        #   decode   bs 桶 [1,8,16,32,64] -> per-shard mnt {1,2,4,8,16}
        #            （MLA wrapper 每次调用同时发 decode 槽和 mixed 槽，所以
        #             小 mnt 的 mixed 条目也要有，否则 decode 步被 fallback 拖住）
        #
        # 调优 2026-09-10，mig-0905 空闲主机 .127（单机 2x2x1，8 device），
        # kv_len=204800，tries=5。基线是硬编码启发式 mixed=(1,16)/decode=(3,1,4)。
        #
        # 提升（纯 kernel device time）：
        #   mixed  mnt=16384: +92.0%  (0.230s vs 2.888s)  <- prefill 热点
        #   mixed  mnt=8192:  +92.0%  (0.113s vs 1.409s)
        #   mixed  mnt=4096:  +92.0%  (0.056s vs 0.696s)
        #   mixed  mnt<=64:   +78~92% (decode 步的空转槽位)
        #   decode mnt=1/2:   +64.6% / +67.8%
        #   decode mnt=4/8/16:+36%
        # 未调优时 200K/c1 的 TTFT 是 253.8s，账能对上：
        #   11 层 x 均长 100K 的 mixed kernel x 13 个 chunk ≈ 206s。
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 1): (32, 1),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 2): (32, 1),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 4): (32, 4),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 8): (32, 8),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 16): (32, 16),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 32): (32, 32),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 64): (32, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 4096): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 8192): (8, 256),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 64, 16384): (8, 256),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 64, 1): (32, 1, 1),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 64, 2): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 64, 4): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 64, 8): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 64, 16): (32, 1, 4),
        # ===== DeepSeek-V3 671B (num_q_heads=128 → 16/shard, kv_lora=512,
        # page=128). decode reuses v6e sweep; mixed bq capped at 128 — v7x
        # scoped VMEM limit is 57.6M (< v6e), bq=256 OOMs by 3.6M at mnt≥256.
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 1): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 8): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 16): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 32): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 64): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 128): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 256): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 512): (32, 1, 2),
        ("decode", "bfloat16", "bfloat16", 16, 512, 64, 128, 1024): (32, 1, 2),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 1): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 8): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 16): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 32): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 64): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 128): (16, 128),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 256): (8, 128),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 512): (8, 128),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 1024): (8, 128),
        ("mixed", "bfloat16", "bfloat16", 16, 512, 64, 128, 2048): (8, 128),
        # ===== GLM-5.2 (tp16: 4 q-heads/shard, kv_lora=512, page=128) =====
        # decode from the DSv3 page-128 family; mixed uses 16-row blocks (bf16
        # tiling needs 16-row alignment at 4 heads/shard; 8-row blocks and the
        # hardcoded fallback both fail Mosaic window setup at mnt>=256).
        # Full mnt bucket coverage pending a tuner sweep.
        ("decode", "bfloat16", "bfloat16", 4, 512, 64, 128, 1): (16, 1, 2),
        ("decode", "bfloat16", "bfloat16", 4, 512, 64, 128, 8): (16, 1, 2),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 1): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 2): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 4): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 8): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 16): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 32): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 64): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 128): (16, 64),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 256): (16, 128),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 512): (16, 128),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 1024): (16, 128),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 2048): (16, 128),
        ("mixed", "bfloat16", "bfloat16", 4, 512, 64, 128, 4096): (16, 128),
        # ===== GLM-5.1 (TP=32) configurations on TPU v7 =====
        # Decode & Mixed tuned for q_head_num=2 (TP=32 sharding)
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 64, 1): (16, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 64, 2): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 64, 4): (64, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 64, 8): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 64, 16): (64, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 64, 32): (64, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 64, 64): (
            64,
            1,
            4,
        ),  # Capped from 128 to prevent VMEM OOM when dbs=4
        ("mixed", "bfloat16", "bfloat16", 2, 512, 64, 64, 8192): (2, 256),
        ("mixed", "bfloat16", "bfloat16", 2, 512, 64, 64, 16384): (2, 256),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 128, 1): (8, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 128, 2): (8, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 128, 4): (16, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 128, 8): (16, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 128, 16): (32, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 128, 32): (
            32,
            1,
            4,
        ),  # Capped from 64 to prevent VMEM OOM when dbs=4
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 128, 64): (32, 1, 4),
        ("mixed", "bfloat16", "bfloat16", 2, 512, 64, 128, 8192): (2, 256),
        ("mixed", "bfloat16", "bfloat16", 2, 512, 64, 128, 16384): (1, 512),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 256, 1): (4, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 256, 2): (8, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 256, 4): (8, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 256, 8): (8, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 256, 16): (8, 1, 4),
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 256, 32): (
            16,
            1,
            4,
        ),  # Capped from 32 to prevent VMEM OOM when dbs=4
        ("decode", "bfloat16", "bfloat16", 2, 512, 64, 256, 64): (
            16,
            1,
            4,
        ),  # Capped from 32 to prevent VMEM OOM when dbs=4
        ("mixed", "bfloat16", "bfloat16", 2, 512, 64, 256, 8192): (1, 512),
        ("mixed", "bfloat16", "bfloat16", 2, 512, 64, 256, 16384): (1, 512),
        # ===== GLM-5.3-Flash (TP=16) on TPU v7x, 200K context =====
        # Deploy: --tp-size 16 --dp-size 1 --page-size 64
        # → attention_tp = 16 → per-shard num_q_heads = 64/16 = 4.
        # Tuned 2026-09-12 on zzl-tpu7x-slice-mig-0905 (v7x, 1 chip / 2 cores)
        # at the shapes this deployment actually runs: kv_len=204800 for both
        # cases, decode mnt=32 (max-running-requests bucket), mixed mnt=16384
        # (chunked-prefill size). Both keys were table misses before, so prod
        # was on the hardcoded fallbacks -- and those fallbacks are very wrong
        # at this context length:
        #   decode: (3, 1, 4) 12.42 ms -> (128, 1, 2) 8.18 ms   (+34%)
        #   mixed:  (1, 16) 2378.93 ms -> (8, 1024)  57.51 ms   (+98%)
        # The mixed fallback reads 64 KV tokens per 16-query block, which at a
        # 200K context is ~3200 grid steps of almost pure DMA latency; that one
        # entry is worth more than everything else in this table put together.
        # The mixed/16384 winner is the (8, 1024) entry already listed in the
        # 4-head block above -- this sweep reproduced it independently.
        ("decode", "bfloat16", "bfloat16", 4, 512, 64, 64, 32): (128, 1, 2),
    },
}


def get_tuned_block_sizes_mla(
    case_label: str,
    q_dtype,
    kv_dtype,
    actual_num_q_heads: int,
    kv_lora_rank: int,
    qk_rope_head_dim: int,
    page_size: int,
    max_num_tokens: int,
) -> tuple | None:
    """Look up the tuned block-size config from the MLA table.

    Args:
        case_label: "decode" or "mixed". The MLA kernel runs
            BATCHED_DECODE+DECODE-tail with a single config (slot[0]) and
            MIXED with another (slot[2]); slot[1] is dead. So callers query
            this function twice — once per case — and combine.
        q_dtype, kv_dtype: tensor dtypes (jax.numpy or numpy dtype).
        actual_num_q_heads: per-shard num q heads (post shard_map).
        kv_lora_rank: model constant; latent KV dim. Not normalized.
        qk_rope_head_dim: model constant; rope head dim. Not normalized.
        page_size: page size in tokens.
        max_num_tokens: padded total token count seen by the kernel
            (= `ql_nope.shape[0]`); already a server-precompiled bucket.

    Returns:
        - For case_label="decode": (num_kv_pages_per_block,
                                    num_queries_per_block,
                                    decode_batch_size) or None on miss.
        - For case_label="mixed":  (num_kv_pages_per_block,
                                    num_queries_per_block) or None on miss.
    """
    if case_label not in ("decode", "mixed"):
        raise ValueError(f"case_label must be 'decode' or 'mixed', got {case_label!r}")

    tpu_version = get_tpu_version()
    if tpu_version < 5:
        return None

    device_name = get_device_name()
    table = TUNED_BLOCK_SIZES_MLA.get(device_name)
    if table is None:
        # Device not supported at all (vs. supported-but-empty, which still
        # logs a miss so operators know to populate it).
        return None

    key = (
        case_label,
        jnp.dtype(q_dtype).name,
        jnp.dtype(kv_dtype).name,
        next_power_of_2(actual_num_q_heads),
        int(kv_lora_rank),
        int(qk_rope_head_dim),
        next_power_of_2(page_size),
        next_power_of_2(max_num_tokens),
    )

    hit = table.get(key)
    if hit is None and key not in _WARNED_MISSES:
        _WARNED_MISSES.add(key)
        logger.info(
            "MLA tuned-block-size LOOKUP MISS device=%s key=%s "
            "(falling back to hardcoded default). Add this key to "
            "TUNED_BLOCK_SIZES_MLA[%s] to enable tuning for this shape.",
            device_name,
            key,
            device_name,
        )
    return hit


def get_fallback_block_sizes_mla(
    case_label: str,
    q_dtype,
    actual_num_q_heads: int,
    page_size: int,
) -> tuple:
    """Tiling-legal hardcoded fallback for tuned-table misses (#1546).

    The historical mixed fallback ``(1, 16)`` implicitly assumed the packed
    q/o layout fills whole sublane tiles: each token occupies
    ``align(num_q_heads, q_packing)`` rows, and the bf16 tile is
    ``8 * q_packing = 16`` rows. With >= 16 q-heads/shard every token fills
    the tile and any block shape is legal; with fewer heads (e.g. GLM-5.2
    tp16 -> 4 heads/shard) token boundaries land inside the tile and Mosaic
    rejects the window at larger mnt buckets
    (E2002 CompileTimeMosaicMisalignedBlockAndTiling).

    For the sub-tile case we return a block from the validated family: a
    q-block covering whole tile groups (``bq * heads_padded`` a multiple of
    ``sublane_tile**2``) and a 2048-token KV block. A table miss should cost
    performance, never a crash.

    Returns ``(num_kv_pages_per_block, num_queries_per_block)`` for both
    cases; the decode fallback keeps the historical ``(3, 1)`` (decode runs
    with ``bq_sz = 1``, no observed illegal geometry).
    """
    if case_label == "decode":
        return (3, 1)
    if case_label != "mixed":
        raise ValueError(f"case_label must be 'decode' or 'mixed', got {case_label!r}")
    q_packing = get_dtype_packing(jnp.dtype(q_dtype))
    sublane_tile = 8 * q_packing
    heads_padded = align_to(actual_num_q_heads, q_packing)
    if heads_padded % sublane_tile == 0:
        # every token fills whole sublane tiles: the historical fallback is
        # legal and keeps prod behaviour unchanged for >=16-head shards.
        return (1, 16)
    num_queries_per_block = max(sublane_tile, (sublane_tile * sublane_tile) // heads_padded)
    num_kv_pages_per_block = max(1, 2048 // page_size)
    return (num_kv_pages_per_block, num_queries_per_block)
